name: 🚀 Deploy to Netlify

on:
  push:
    branches:
      - master  # au main, angalia branch yako

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node (kama utahitaji, unaweza ondoa kama sio lazima)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./  # sehemu ilipo index.html
          production-branch: master  # au main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 Auto-deployed via GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
